---
Formação Cientista de Dados - Prof. Fernando Amaral
SEÇÃO 9: Limpeza e Tratamento de Dados
---

Tratar dados 'tempo.csv'
   Aparência: sol, nublado, chuva
   Temperatura: -130 ~ 130 F
   Umidade: 0 ~ 100
   Vento: Verdadeiro/Falso
   Jogar: sim/nao
   
**Tratar valores NA


```{r}
dados = read.csv("tempo.csv", sep = ";", na.strings="", stringsAsFactors=T)
```

1. Explorando os dados
```{r}
print("Aparência")
counts = table(dados$Aparencia)
counts

summary(dados$Aparencia)

#Gráfico
barplot(counts, xlab="Aparência", ylab = "Quantidade de dias")

#Foi notada uma anormalidade (menos) nesta coluna
```

```{r}
print("Temperatura")
counts = table(dados$Temperatura)
counts

summary(dados$Temperatura)

#Gráfico
barplot(counts, xlab="Temperatura", ylab="Quantidade de dias")

#Foi notada uma anormalidade (1220) nesta coluna
```

```{r}
print("Umidade")
counts = table(dados$Umidade)
counts

summary(dados$Umidade)

#Gráfico
barplot(counts,xlab="Umidade", ylab = "Quantidade de dias")

#Foi notada uma anormalidade (200) e um valor NA nesta coluna
```
```{r}
print("Vento")
counts = table(dados$Vento)
counts

summary(dados$Vento)

#Gráfico
barplot(counts, xlab="Tipo de vento", ylab="Quantidade de dias")

#Foi notado um valor NA nesta coluna
```


```{r}
print("Jogar")
counts = table(dados$Jogar)
counts

#Gráfico
barplot(counts, xlab="Jogar", ylab="Quantidade")

#Nenhum valor NA e nem anormalidade
```

```{r}
summary(dados)
```
Tratando Valores anormais e NAs

```{r}
#Aparência

#Não possui valores NAs
summary(dados$Aparencia)

#Substituir valor anormal pela moda descoberta através de "summary"
dados[dados$Aparencia == 'menos' ,]$Aparencia = 'sol' 


#remover level não mais utilizado (menos)
dados$Aparencia =   factor(dados$Aparencia)

#Verificação
summary(dados$Aparencia)
```


```{r}
#Temperatura

dados[dados$Temperatura < -130 | dados$Temperatura > 130 ,]$Temperatura

#Verificando se possui valores NA
dados[is.na(dados$Temperatura),]

#Descobrindo a mediana para substituir valores anormais por ela
median(dados$Temperatura)

#Substituição
dados[dados$Temperatura < -130 | dados$Temperatura > 130 ,]$Temperatura = median(dados$Temperatura) 

#Verificação
dados[dados$Temperatura < -130 | dados$Temperatura > 130 ,]$Temperatura
```

```{r}
#Umidade

dados[dados$Umidade > 0 | dados$Umidade < 100 ,]$Umidade

#Verificando se possui valores NA (AQUI POSSUI VALORES NA)
dados[is.na(dados$Umidade),]

#Descobrindo a mediana paramsubstituir valores anormais por ela
median(dados$Umidade)

#Substituição de NAs
dados[is.na(dados$Umidade),]$Umidade = median(dados$Umidade,na.rm = T)

#subtituição de dados Anormais
dados[dados$Umidade < 0 | dados$Umidade > 100 ,]$Umidade = median(dados$Umidade)

#Verificação
dados[dados$Umidade > 0 | dados$Umidade < 100 ,]$Umidade
```

```{r}
#Vento

#Possui valores NAs obs: pode usar dados[is.na(dados$Umidade),] 
summary(dados$Vento)

#Substituir valor NA pela moda descoberta através de "summary"
dados[is.na(dados$Vento),]$Vento = 'FALSO' 

#Verificação
summary(dados$Vento)


```

